extends RefCounted
const CODES := ["en","de","fr","es","it","sr"]
const NAMES := {"en":"English","de":"Deutsch","fr":"Français","es":"Español","it":"Italiano","sr":"Srpski"}
const POOLS := {
	"de":"EEEEEEEEEEEEEEEENNNNNNNNNIIIIIIIRRRRRRSSSSSSTTTTTTAAAAAADDDDDHHHHUUUULLLLCCCGGMMOOBWWFFKZPVJYQXÄÖÜ",
	"fr":"EEEEEEEEEEEEEEEAAAAAAAIIIIIIIISSSSSSSNNNNNNTTTTTTRRRRRRUUUUUULLLLLOOOOODDMMCCPPVVQFBGHJXYZKWÉÉÈÊËÀÂÎÏÔÙÛÜÇ",
	"es":"AAAAAAAAAAAAEEEEEEEEEEEEOOOOOOOOOSSSSSSNNNNNRRRRRIIIIIILLLLDDDDTTTCCCUUUMMPPBBGGVVYQHFJZÑÁÉÍÓÚÜKWX",
	"it":"EEEEEEEEEEEEAAAAAAAAAAAIIIIIIIIIIIOOOOOOOONNNNNNLLLLLLRRRRRRTTTTTSSSSCCCDDDPPPMMUUUVVBGFZHQJKWXYÀÈÉÌÒÙ"
}
const STARTERS := {
	"de":["STEIN","WASSER","FEUER","GARTEN","KRONE","STURM","LICHT","TRAUM","WOLKE","WALD","MOND","BLUME"],
	"fr":["PIERRE","FLEUVE","JARDIN","FLAMME","NUAGE","MONDE","ÉTOILE","LUMIÈRE","FORÊT","FLEUR","OMBRE","LIVRE"],
	"es":["PIEDRA","FUEGO","JARDÍN","CORONA","NUBE","MUNDO","SOL","BOSQUE","FLOR","SOMBRA","LIBRO","PUENTE"],
	"it":["PIETRA","ACQUA","FUOCO","CORONA","NUVOLA","MONDO","STELLA","LUCE","BOSCO","FIORE","OMBRA","PONTE"]
}
static func record_key(key: String) -> bool:
	return key.get_slice("_",0) in CODES and key.get_slice("_",1) in ["adjacent","any"]
