/* Samostalan atlas: bez servera, zavisnosti, telemetrije i trajnog čuvanja. */
const $ = s => document.querySelector(s);
const esc = s => String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const byId = id => SCREENS.find(s=>s.id===id);
let current = byId(location.hash.slice(1))?.id || 'battle', view = 'play', filter = '', settingsReturn = 'home';
let demo = {energy:13,hp:76,enemy:64,used:[],chosen:[],letters:['M','O','S','T','A','R','I'],shield:false,sets:0};
const positions=[[105,0],[180,34],[198,111],[143,155],[65,155],[12,111],[30,34]];
const btn=(text,to,style='primary')=>`<button class="game-btn ${style}" data-go="${to}">${text}</button>`;
const act=(text,action,style='primary')=>`<button class="game-btn ${style}" data-action="${action}">${text}</button>`;
function creature(type='mint',extra='') {
 const colors={mint:['#c7f2cc','#69b79e','#1d5053'],coral:['#f0b092','#b96867','#613b4d'],gold:['#fae8a1','#c2a66a','#685c4c'],dark:['#729e92','#375659','#19383d']};
 const [a,b,c]=colors[type]||colors.mint;
 return `<svg class="creature ${extra}" viewBox="0 0 140 130" role="img" aria-label="${{mint:'Iskra, mali svetleći odjek',coral:'Čuvar sa kamenim oklopom',gold:'Zvono, odjek kontrole',dark:'Neotkrivena silueta odjeka'}[type]}"><ellipse cx="70" cy="115" rx="43" ry="8" fill="#071d27" opacity=".4"/><path d="M37 58 Q17 18 36 11 Q51 11 59 43 L81 41 Q101 7 113 20 Q119 39 99 59Z" fill="${b}" stroke="${c}" stroke-width="3"/><path d="M40 45 Q69 29 99 49 Q123 77 106 106 Q79 124 41 108 Q20 91 40 45Z" fill="${b}" stroke="${c}" stroke-width="3"/><path d="M42 67 Q65 48 94 64 Q112 86 94 106 Q64 120 42 99Z" fill="${a}"/><path d="M38 95 Q10 83 16 72 Q30 72 42 84 M102 88 Q125 69 128 83 Q124 97 105 101" fill="${b}" stroke="${c}" stroke-width="3"/><path d="M42 105 Q28 115 40 120 L57 116 M84 115 Q110 126 108 113 L99 104" fill="${b}" stroke="${c}" stroke-width="3"/><ellipse cx="55" cy="78" rx="5" ry="8" fill="${c}"/><ellipse cx="87" cy="77" rx="5" ry="8" fill="${c}"/><circle cx="56" cy="75" r="1.5" fill="#fff9d9"/><circle cx="88" cy="74" r="1.5" fill="#fff9d9"/><path d="M66 90 Q72 97 78 90" fill="none" stroke="${c}" stroke-width="3" stroke-linecap="round"/><path d="M62 51 L71 33 L80 51 L71 62Z" fill="#f5db98"/><path d="M53 37 Q50 20 45 18 M94 37 L103 26" stroke="${a}" stroke-width="4" fill="none" stroke-linecap="round"/></svg>`;
}
function scenery(){return `<svg class="game-art scenery" viewBox="0 0 360 250" preserveAspectRatio="xMidYMid slice" role="img" aria-label="Plutajuća ostrva i svetionik u svetlećoj magli"><defs><linearGradient id="sky-${scenery.n=(scenery.n||0)+1}" x2="0" y2="1"><stop stop-color="#183c46"/><stop offset="1" stop-color="#35665a"/></linearGradient></defs><path fill="#244d51" d="M0 0H360V250H0Z"/><circle cx="260" cy="45" r="28" fill="#cfddb0" opacity=".65"/><path d="M0 173L46 73 101 155 155 68 201 146 254 102 360 173V250H0" fill="#2e5a58"/><path d="M0 213Q65 163 128 198T250 174T360 194V250H0" fill="#1b4247"/><path d="M65 160L187 144 247 170 184 210 99 200Z" fill="#122e37"/><path d="M65 160L139 142 216 149 247 170 173 181 107 176Z" fill="#527d5e"/><path d="M136 147L145 82 174 82 190 152Z" fill="#b0b99b"/><path d="M143 86L143 68 176 68 178 88Z" fill="#d8d2a4"/><path d="M136 69L160 47 183 69Z" fill="#244847"/><path d="M151 74H168V86H151Z" fill="#f5dc91"/><path d="M154 118H170V143H154Z" fill="#315551"/><path d="M134 146L162 154 187 148" fill="none" stroke="#ded49c" stroke-width="3"/><path d="M247 116L310 111 328 122 280 144Z" fill="#193a40"/><path d="M247 116L277 104 310 111 328 122 281 128Z" fill="#537e65"/><path d="M31 83L72 76 97 89 52 108Z" fill="#1a3b43"/><path d="M31 83L54 71 72 76 97 89 56 93Z" fill="#668467"/><g fill="#dbd998"><circle cx="45" cy="139" r="2"/><circle cx="298" cy="70" r="2"/><circle cx="207" cy="98" r="1.5"/><circle cx="121" cy="106" r="2"/><circle cx="321" cy="178" r="2"/><circle cx="31" cy="39" r="1.5"/></g><path d="M0 238Q60 205 110 232T224 221T360 232" stroke="#83ae8c" opacity=".15" stroke-width="21" fill="none"/></svg>`}
function gameTop(title,back='home',sub=''){return `<div class="game-top"><button class="back" data-go="${back}" aria-label="Nazad">‹</button><div class="game-title">${title}${sub?`<small>${sub}</small>`:''}</div><span class="currency">◈ 240</span></div>`}
function nav(active='home'){return `<nav class="bottom-nav" aria-label="Navigacija igre">${[['home','⌂','Baza'],['map','⌁','Mapa'],['collection','◇','Odjeci'],['workshop','⚒','Radionica']].map(([id,ic,t])=>`<button data-go="${id}" class="${active===id?'on':''}"><b>${ic}</b>${t}</button>`).join('')}</nav>`}
function row(icon,title,sub,to){return `<button class="game-row" data-go="${to}"><b class="icon-box">${icon}</b><span class="row-copy">${title}<small>${sub}</small></span><span>›</span></button>`}
function card(title,text,extra=''){return `<div class="game-card"><h3>${title}</h3><p class="lead">${text}</p>${extra}</div>`}
function team(){return `<div class="team-row">${[['mint','Iskra','Udarac · 6'],['gold','Ljuska','Štit · 5'],['coral','Zvono','Prekid · 10']].map(([c,n,t])=>`<button class="team-slot" data-go="ability">${creature(c)}<b>${n}</b><div class="mini-label">${t}</div></button>`).join('')}</div>`}
function phone(s){return `<div class="phone"><div class="statusbar"><span>9:41</span><span>▴ ▰</span></div><div class="screen" data-screen="${s.id}">${render(s)}</div><div class="home-indicator"></div></div>`}
function battle(d={},tutorial=false){
 const energy=d.energy??13,hp=d.hp??76,letters=d.board||['M','O','S','T','A','R','I'];
 const selected=d.selected||[];
 return `<div class="battle-head"><div class="row"><span class="section-kicker">${d.boss?'ČUVAR TIŠINE · BOSS':'SVETLUCAVI GAJ · 03'}</span><button class="small-btn" data-go="pause" aria-label="Pauziraj borbu">Ⅱ</button></div><div class="fighter-stats"><div><strong>Tvoj odjek</strong><div class="meter"><i style="width:${hp}%"></i></div><small id="hp-value">${hp}/100</small></div><span class="versus">vs</span><div class="enemy"><strong>${d.boss?'Čuvar tišine':'Mrmljavac'}</strong><div class="meter"><i id="enemy-bar" style="width:80%"></i></div><small id="enemy-value">64/80</small></div></div></div>
 <div class="battle-stage">${scenery()}${creature('mint')}${creature(d.boss?'dark':'coral','foe')}${d.effect?`<span style="position:absolute;right:60px;top:16px;color:var(--gold);font-size:30px">${d.effect}</span>`:''}${d.shield?'<span class="pill" style="position:absolute;left:25px;top:28px">◇ ŠTIT</span>':''}</div>
 <div class="attack-warning"><span>△ ${d.warning||'Protivnik priprema udar'}</span><b>${d.warning?'':'8 s'}</b></div>
 <div class="energy-row"><span>✧ ENERGIJA <strong id="energy-value">${energy}/30</strong></span><span id="set-count">${d.id==='word-ok'?'2':'1'}/3 reči → nova slova</span></div>
 <div class="abilities">${[['⚡','Udarac',6,'hit'],['◇','Štit',5,'shield'],['〰','Prekid',10,'interrupt']].map(([icon,name,cost,action])=>`<button class="ability" data-action="${action}" aria-label="${name}, ${cost} energije"><b>${icon}</b><span>${name}</span><small>${d.cooldown&&action==='interrupt'?'15 s · oporavak':`${cost} energije`}</small></button>`).join('')}</div>
 <div class="word-zone"><div class="word-value" id="word-value">${d.word||'· · ·'}</div><div class="word-message ${d.error?'error':''}" id="word-message" role="status">${d.message||'Poveži slova. Oslobodi njihov glas.'}</div></div>
 <div class="letters" aria-label="Tabla od sedam slova"><svg class="letter-line" viewBox="0 0 262 205" aria-hidden="true"><polyline points="${selected.map(i=>`${positions[i][0]+25.5},${positions[i][1]+25.5}`).join(' ')}"/></svg><div class="letter-center">${tutorial?'PRVA REČ':'ODJEK'}<br>✧</div>${letters.map((l,i)=>`<button class="letter ${selected.includes(i)?'selected':''}" data-letter="${i}" style="left:${positions[i][0]}px;top:${positions[i][1]}px" aria-label="Slovo ${l}">${l}</button>`).join('')}</div>
 <div class="board-actions"><button data-action="shuffle">↻ Mešaj</button><button data-action="submit">Potvrdi</button><button data-action="replace">Nova slova</button></div>`;
}
function render(s){const d=s.data;switch(s.kind){
 case 'splash':return `<div class="content center"><div style="padding-top:35px" class="section-kicker">SVAKA REČ BUDI SVET</div><div class="hero-copy"><h2 style="font-size:59px;margin:24px 0">War<br><i>of Words</i></h2><p>Priče počinju jednom iskrom.</p></div><div class="landscape" style="height:280px">${scenery()}</div>${btn('Započni putovanje','language')}${btn('Nastavi putovanje','home','ghost')}<p class="mini-label" style="margin-top:20px">Radni naziv · vizuelni predlog 01</p></div>`;
 case 'language':return `${gameTop('Tvoj jezik','splash')}<div class="content"><span class="section-kicker">PRE PRVE REČI</span><h2>Na kom jeziku<br>svet govori?</h2><p class="lead">Jezik menija i jezik reči mogu biti različiti.</p><label class="field-label">Jezik interfejsa<select class="game-select"><option>Srpski · latinica</option><option>Српски · ћирилица — predlog</option><option>English — predlog</option></select></label><label class="field-label">Rečnik za borbu<select class="game-select"><option>Srpski · latinica / demo</option><option disabled>Srpski · ćirilica / budući paket</option><option disabled>English / budući paket</option></select></label>${card('Slova imaju svoj glas.','Č, Ć, Š, Ž i Đ su različita slova. LJ, NJ i DŽ zahtevaju posebno pravilo pre izrade rečnika.')}<p class="mini-label">Ovo je pregled izbora. Demo ekrani ostaju na srpskoj latinici.</p>${btn('Dalje','profile')}</div>`;
 case 'profile':return `${gameTop('Novi istraživač','language')}<div class="content center"><span class="section-kicker">DOBRO DOŠAO U SVETIONIK</span>${creature('mint','large')}<h2>Kako da te zovemo?</h2><p class="lead">Odjeci pamte glasove svojih prijatelja.</p><label class="field-label" style="text-align:left">Ime istraživača<input class="game-input" id="player-name" maxlength="16" value="Luka" autocomplete="off"></label><p class="mini-label">Do 16 znakova · možeš promeniti kasnije.<br>Lokalni profil, bez obavezne prijave.</p>${act('Krenimo','profile-next')}</div>`;
 case 'story':return `${gameTop('Priča','map')}<div class="content"><div class="landscape">${scenery()}</div><span class="section-kicker">${d.speaker}</span><h2>${d.heading}</h2><p class="lead">${d.text}</p>${btn('Nastavi',d.next)}${btn('Preskoči priču',d.next,'ghost')}</div>`;
 case 'tutorial':return `<div class="game-top"><span class="game-title">Prva iskra <small>KORAK ${d.step} OD 3</small></span><button class="small-btn" data-go="home">Preskoči</button></div><div class="content"><div class="progress-steps">${[1,2,3].map(i=>`<i class="${i<=d.step?'on':''}"></i>`).join('')}</div><h2>${d.heading}</h2><p class="lead">${d.text}</p>${d.step===1?`<div class="word-zone"><div class="word-value" id="word-value">· · ·</div><div id="word-message" class="word-message" role="status">Poveži M → O → S → T</div></div><div class="letters"><svg class="letter-line" viewBox="0 0 262 205" aria-hidden="true"><polyline/></svg>${demo.letters.map((l,i)=>`<button class="letter" data-letter="${i}" style="left:${positions[i][0]}px;top:${positions[i][1]}px">${l}</button>`).join('')}</div>${act('Potvrdi reč','submit','')}`:`${creature(d.step===2?'mint':'coral','large')}${card(d.step===2?'MOST → +5 energije':'△ Snažan udar za 3 sekunde',d.step===2?'Duže reči pune više energije. Napad biraš sam.':'Štit: 5 energije. Prekid: 10 energije.')}`}${btn(d.step===3?'Spreman sam':'Sledeći korak',d.next)}</div>`;
 case 'home':return `<div class="game-top"><button class="back" data-go="save" aria-label="Profil">L</button><div class="game-title">Dobro došao, Luka<small>ISTRAŽIVAČ · NIVO 4</small></div><span class="currency">◈ 240</span><button class="back" data-go="settings" aria-label="Podešavanja">⚙</button></div><div class="content"><div class="landscape"><div class="hero-copy"><span class="section-kicker">TVOJE MESTO U SVETU</span><h2>Svetionik<br><i>odjeka</i></h2></div>${scenery()}<div class="hero-badge"><span>SVETLUCAVI GAJ</span><span>3 / 7 susreta</span></div></div>${btn('Nastavi ekspediciju  →','map')}<div class="game-card"><div class="row"><div><span class="section-kicker">SLEDEĆI CILJ</span><h3>Probudi stari most</h3><small>Prođi kroz Svetlucavi gaj.</small></div><span class="stat">03</span></div></div><div class="row"><span class="section-kicker">TVOJI ODJECI</span><button class="game-btn inline ghost" data-go="team">Promeni ›</button></div>${team()}<div class="two-col">${btn('✧ Zadaci','quests','')}${btn('⌁ Dnevnik','codex','')}</div></div>${nav()}`;
 case 'map':return `${gameTop('Svetlucavi gaj','home','OBLAST 01 / 04')}<div class="content"><div class="row"><h2>Prati odjek.</h2><span class="pill gold">3 / 7</span></div><p class="lead">Svaki korak vraća malo svetlosti.</p><div class="map-area"><svg class="map-path" viewBox="0 0 350 377" aria-hidden="true"><path d="M77 328 C210 330 275 276 228 241 S30 224 105 167 S280 132 242 88 S126 73 162 27" fill="none" stroke="#91b894" stroke-width="3" stroke-dasharray="5 9"/><path d="M0 110Q70 64 107 110T200 80T350 119M0 300Q70 250 130 277T350 260" fill="none" stroke="#3f74634d" stroke-width="28"/></svg>${[[53,299,'✓'],[147,269,'✓'],[211,218,'3'],[133,170,'4'],[70,139,'5'],[216,65,'6'],[143,4,'♜']].map(([x,y,n],i)=>`<button class="map-node ${i===2?'next':i>2?'lock':''}" style="left:${x}px;top:${y}px" data-go="${i>2?'region-locked':'encounter'}" aria-label="Susret ${n}${i>2?', zaključan':''}">${n}</button>`).join('')}<span class="map-label" style="left:20px;top:242px">Svetionik</span><span class="map-label" style="left:198px;top:7px">Čuvar tišine</span></div>${btn('Susret 03 · Šapat u korenju','encounter')}${btn('Pogledaj ostrva','world','ghost')}</div>${nav('map')}`;
 case 'world':return `${gameTop('Atlas ostrva','map')}<div class="content"><span class="section-kicker">PUTOVANJE TEK POČINJE</span><h2>Iza svake magle,<br>novi glas.</h2><div class="landscape" style="height:190px">${scenery()}</div>${row('01','Svetlucavi gaj','3 / 7 susreta · otkriven','map')}${row('02','Stakleni plićaci','Pobedi Čuvara tišine','region-locked')}${row('03','Radionice vetra','Neotkrivena oblast','region-locked')}${row('04','More bez imena','Neotkrivena oblast','region-locked')}</div>${nav('map')}`;
 case 'encounter':return `${gameTop('Susret 03','map')}<div class="content"><span class="section-kicker">SVETLUCAVI GAJ</span><h2>Šapat u korenju</h2>${creature('coral','large')}<div class="row"><h3>Mrmljavac</h3><span class="pill red">80 zdravlja</span></div>${card('△ Spor, ali uporan','Najavljuje udar. Sačuvaj 5 energije za štit ili 10 za prekid.')}<div class="row"><span class="section-kicker">TVOJ IZBOR</span><button class="small-btn" data-go="team">Izmeni</button></div>${team()}<p class="mini-label">Prva pobeda: ◈ 60 svetlopraha + nacrt.</p>${btn('Započni susret','battle')}</div>`;
 case 'team':return `${gameTop('Tvoja trojka','encounter')}<div class="content"><h2>Tri glasa.<br>Jedna taktika.</h2><p class="lead">Jedan napad, jedan štit i jedan prekid za prvi test.</p>${team()}${row('⚡','Iskra · direktan udar','6 energije · 10 štete','ability')}${row('◇','Ljuska · zaštita','5 energije · ublažava 8 štete','ability')}${row('〰','Zvono · prekid','10 energije · otkazuje najavu','ability')}${card('Kasniji izbori','Sistem zamene članova je predlog. Ovde pregledaš tri početne uloge, bez menjanja balansa.')}${btn('Potvrdi postavu','encounter')}</div>`;
 case 'battle':return battle({...d,id:s.id});
 case 'modal':return `${render(byId(d.base))}<div class="modal-shade"><section class="modal" role="dialog" aria-modal="true" aria-label="${esc(d.heading)}"><div class="modal-symbol">${d.symbol}</div><h2>${d.heading}</h2><p>${d.text}</p>${btn(...d.primary)}${d.secondary?btn(...d.secondary,''):''}${d.tertiary?btn(...d.tertiary,'ghost'):''}</section></div>`;
 case 'boss':return `${gameTop('Stari koren','map','POSLEDNJI SUSRET')}<div class="content center"><span class="pill red">ČUVAR OBLASTI</span>${creature('dark','large')}<h2 class="result-title">Čuvar<br><i>tišine</i></h2><p class="lead">Ne želi tvoje reči.<br>Želi da zauvek prestaneš da govoriš.</p>${card('Dve faze. Dva odgovora.','Na pola zdravlja priprema dva udara. Zaštiti se ili prekini njegovu najavu.')}${btn('Suoči se sa čuvarom','boss-phase')}${btn('Vrati se na stazu','map','ghost')}</div>`;
 case 'victory':return `${gameTop('Susret završen','map')}<div class="content center"><span class="section-kicker">SVETLUCAVI GAJ · 03</span><div class="stars">✦ ✦ ✦</div><h2 class="result-title">Svet te čuje.</h2>${creature('mint','large')}<p class="lead">Most ponovo pamti svoje ime.</p><div class="game-card"><div class="row"><span>◈ Svetloprah</span><strong class="stat">+60</strong></div><hr class="divider"><div class="row"><span>Najduža reč</span><strong>MOST</strong></div></div><div class="two-col"><div><span class="stat">12</span><div class="mini-label">prihvaćenih reči</div></div><div><span class="stat">3</span><div class="mini-label">odbranjena udara</div></div></div>${btn('Otkrij nagradu','reward')}${btn('Pregled borbe','battle-summary','ghost')}</div>`;
 case 'defeat':return `${gameTop('Susret završen','map')}<div class="content center"><div class="large-symbol">☾</div><h2 class="result-title">Još nije<br>kraj priče.</h2><p class="lead">Čuvar je ovog puta sačuvao svoj prolaz.</p>${card('Mali pomak, velika razlika','Dva snažna udara su prošla bez zaštite. Sledeći put sačuvaj 5 energije za štit.')}${creature('mint')}<p class="mini-label">Raniji napredak je sačuvan.</p>${btn('Pokušaj ponovo','battle')}${btn('Pregledaj sposobnosti','team','')}${btn('Nazad na mapu','map','ghost')}</div>`;
 case 'summary':return `${gameTop('Tvoj trag u borbi','victory')}<div class="content"><span class="section-kicker">POBEDA · 01:42</span><h2>Svaka reč<br>je pomogla.</h2><div class="two-col">${card('12','prihvaćenih reči')}${card('54','prikupljene energije')}</div>${row('⚡','4 udarca','24 potrošene energije','ability')}${row('◇','3 uspešna štita','15 potrošene energije','ability')}${row('〰','1 prekid','10 potrošene energije','ability')}${card('Reči koje su otvorile put','MOST · MAST · RAT · MIR · SAT · MORA')}<p class="mini-label">Prikazan je ilustrativni sažetak, nezavisan od demo borbe.</p>${btn('Nedostaje neka reč?','word-report','')}${btn('Nastavi','reward')}</div>`;
 case 'reward':return `${gameTop('Nagrada prve pobede','victory')}<div class="content center"><span class="section-kicker">PRONAĐENO U STAROM KORENU</span><div class="reward-orb">◇</div><h2>Nešto se<br>budi unutra.</h2><p class="lead">Nacrt Zvona — odjeka koji prekida protivnički napad.</p>${card('Garantovano otkriće','Ovu nagradu dobijaš za prvu pobedu. Nema kupovine niti nasumičnog izvlačenja.')}${btn('Probudi odjek','new-echo')}${btn('Kasnije · nazad na mapu','map','ghost')}</div>`;
 case 'unlock':return `${gameTop('Novo otkriće','reward')}<div class="content center"><span class="pill gold">NOVI ODJEK</span>${creature('gold','large')}<h2 class="result-title">Zvono</h2><span class="section-kicker">KONTROLA · GLAS KOJI ZAUSTAVLJA</span>${card('〰 Prekid','Za 10 energije otkazuje najavljeni napad. Oporavak: 15 sekundi.')}${btn('Pregledaj postavu','team')}${btn('Detalji sposobnosti','ability','')}</div>`;
 case 'choice':return `${gameTop('Razvij svoj stil','ability')}<div class="content"><h2>Kako tvoj<br>štit odgovara?</h2><p class="lead">Izaberi jednu od dve taktičke grane.</p>${card('◇ Postojana ljuska','Ublažava 10 umesto 8 štete. Za mirniji, sigurniji ritam.',btn('Izaberi jaču zaštitu','upgrade-strong-confirm',''))}${card('✧ Povratni odjek','Pravovremen štit vraća 2 energije. Za precizan odgovor i brži napad.',btn('Izaberi povraćaj energije','upgrade-confirm'))}<p class="mini-label">Obe grane su predlozi za testiranje.</p></div>`;
 case 'chapter':return `${gameTop('Prva oblast završena','world')}<div class="content center"><span class="section-kicker">SVETLUCAVI GAJ PONOVO PEVA</span><div class="landscape">${scenery()}</div><h2 class="result-title">Tišina<br>je popustila.</h2><p class="lead">Sedam susreta. Novi prijatelji.<br>Jedno ostrvo koje ponovo ima glas.</p>${card('Otkriven novi put','Stakleni plićaci · oblast 02')}${btn('Pogledaj šta je iza magle','world')}</div>`;
 case 'collection':return `${gameTop('Tvoji odjeci','home','3 OTKRIVENA / 6 U KONCEPTU')}<div class="content"><h2>Mali glasovi.<br>Velike mogućnosti.</h2><div class="row"><span class="pill gold">Svi odjeci</span><button class="small-btn" data-go="collection-empty">Neopremljeni</button></div><div class="two-col" style="margin-top:15px">${[['mint','Iskra','NAPAD'],['gold','Ljuska','ODBRANA'],['coral','Zvono','KONTROLA'],['dark','???','NEOTKRIVENO']].map(([c,n,r])=>`<button class="game-card center" data-go="${c==='dark'?'collection-locked':'ability'}">${creature(c)}<h3>${n}</h3><small>${r}</small><div style="margin-top:7px" class="pill">${c==='dark'?'Oblast 02':'U postavi'}</div></button>`).join('')}</div>${btn('Uredi postavu','team')}</div>${nav('collection')}`;
 case 'ability':return `${gameTop('Ljuska','collection','ODJEK ODBRANE')}<div class="content center">${creature('gold','large')}<h2>Mir usred udara.</h2><span class="pill gold">NIVO 2 · U POSTAVI</span><div class="game-card"><div class="row"><b>◇ Štit</b><span class="currency">5 energije</span></div><p class="lead" style="margin-top:10px">Ublažava 8 štete od sledećeg napada. Ponovno aktiviranje ne sabira zaštitu.</p></div><div class="two-col">${card('8 → 10','zaštita, jača grana')}${card('+2','energije, povratna grana')}</div>${btn('Uporedi grane','upgrade-choice')}${btn('Pregledaj unapređenje','upgrade-cost','')}${btn('Nazad u postavu','team','ghost')}</div>`;
 case 'detail-locked':return `${gameTop('Neotkriven odjek','collection')}<div class="content center">${creature('dark','large')}<h2>Neki glasovi<br>čekaju strpljivo.</h2><p class="lead">Odjek Staklenih plićaka.</p>${card('Trag do otkrića','Završi prvi susret u oblasti 02. Sposobnost se otkriva kroz napredovanje.')}${btn('Pogledaj put','map')}</div>`;
 case 'empty':return `${gameTop(s.title,'home')}<div class="content center"><div class="large-symbol">${d.symbol}</div><h2>${d.heading}</h2><p class="lead" style="margin:20px 0 32px">${d.text}</p>${btn(...d.primary)}${d.secondary?btn(...d.secondary,''):''}</div>`;
 case 'workshop':return `${gameTop('Radionica','home')}<div class="content"><span class="section-kicker">SVETLOPRAH DOBIJA OBLIK</span><h2>Učini dobru<br>ideju snažnijom.</h2>${creature('gold','large')}${row('◇','Ljuska · nivo 2 → 3','120 svetlopraha · dostupno','upgrade-cost')}${row('⚡','Iskra · nivo 3 → 4','Nacrt iz Staklenih plićaka','collection-locked')}${row('〰','Zvono · nivo 1','Pregled i taktičke grane','ability')}${btn('Otvori ranac','inventory','')}</div>${nav('workshop')}`;
 case 'upgrade-cost':return `${gameTop('Unapredi Ljusku','workshop')}<div class="content center">${creature('gold','large')}<h2>Čvršća zaštita.</h2><div class="game-card"><div class="row"><span>Nivo</span><b>2 → 3</b></div><hr class="divider"><div class="row"><span>Ublažena šteta</span><b>8 → 10</b></div><hr class="divider"><div class="row"><span>Cena sposobnosti</span><b>5 → 5 energije</b></div></div><p class="lead">Cena: ◈ 120 svetlopraha<br>Imaš: ◈ 240 · posle: ◈ 120</p>${btn('Unapredi za 120','upgrade-done')}${btn('Nazad','workshop','ghost')}</div>`;
 case 'upgrade-done':return `${gameTop('Nadogradnja završena','workshop')}<div class="content center"><span class="pill gold">LJUSKA · NIVO 3</span>${creature('gold','large')}<h2>Spremna za<br>sledeći udar.</h2>${card('Zaštita 8 → 10','Cena u borbi ostaje 5 energije. Prikazan primer numeričke nadogradnje.')}${btn('Isprobaj na sledećem susretu','map')}${btn('Pogledaj postavu','team','')}</div>`;
 case 'inventory':return `${gameTop('Ranac','workshop')}<div class="content"><h2>Sve što si<br>doneo sa puta.</h2>${row('◈','Svetloprah · 240','Materijal za unapređenja','item-detail')}${row('◇','Nacrt Zvona · 1','Otključava odjek kontrole','new-echo')}${row('✧','Svetlosno seme · 2','Ukras svetionika','cosmetics')}${card('Mesto za svako otkriće','U predlogu nema ograničenja prostora u rancu.')}</div>`;
 case 'item':return `${gameTop('Svetloprah','inventory')}<div class="content center"><div class="reward-orb">◈</div><h2>Svetlo koje<br>ostaje u rukama.</h2><span class="pill gold">240 U RANCU</span>${card('Čemu služi','Koristi se u radionici za unapređenje odjeka.')}${card('Gde ga pronaći','Garantovana nagrada susreta i stalnih ciljeva ekspedicije.')}${btn('Idi u radionicu','workshop')}</div>`;
 case 'quests':return `${gameTop('Zadaci ekspedicije','home')}<div class="content"><h2>Male reči.<br>Veliki koraci.</h2><p class="lead">Napreduj svojim tempom. Ciljevi ne ističu.</p>${card('Reči grade mostove','Sastavi 10 različitih reči · 10/10',btn('Preuzmi ◈ 40','quest-reward'))}${card('Mirna ruka','Odbrani 5 najavljenih udara · 3/5','<div class="meter"><i style="width:60%"></i></div>')}${card('Glas daljine','Otkrij sledeću oblast · 0/1',btn('Pogledaj mapu','map',''))}</div>`;
 case 'training':return `${gameTop('Slobodan trening','home')}<div class="content"><span class="section-kicker">BEZ SATA · BEZ KAZNE</span><h2>Pronađi<br>svoj ritam.</h2>${creature('mint','large')}<p class="lead">Ispitaj reči i redosled sposobnosti. Trening ne troši materijal i ne daje nagrade.</p><label class="field-label">Vežba<select class="game-select"><option>Reči i tri sposobnosti</option><option>Duže reči — koncept</option><option>Pravovremen štit — koncept</option></select></label>${act('Započni mirnu probu','training')}${btn('Pravila rečnika','dictionary','ghost')}</div>`;
 case 'training-results':return `${gameTop('Trening završen','training')}<div class="content center"><div class="large-symbol">✧</div><h2>Svakim pokušajem<br>malo sigurniji.</h2><div class="two-col">${card('8','različitih reči')}${card('MOST','najduža reč')}</div>${card('Reči ove vežbe','MOST · MAST · MIR · RAT · SAT · MORA · STO · TRI')}<p class="mini-label">Ilustrativni izveštaj. Nema nagrada u treningu.</p>${btn('Još jedna vežba','training')}${btn('Nazad u bazu','home','')}</div>`;
 case 'codex':return `${gameTop('Dnevnik sveta','home')}<div class="content"><h2>Sve što<br>tišina skriva.</h2><div class="landscape" style="height:180px">${scenery()}</div>${row('⌁','Svetlucavi gaj','Oblast · otkriveno','world')}${row('◇','Mrmljavac','Protivnik · proučen','enemy-detail')}${row('♜','Čuvar tišine','Čuvar oblasti · trag','boss-intro')}${row('?','Neispisana stranica','Nastavi ekspediciju','map')}</div>`;
 case 'enemy-detail':return `${gameTop('Mrmljavac','codex')}<div class="content">${creature('coral','large')}<h2>Glasan kad<br>misli da ga nemaš.</h2>${card('Obrazac','Spor, najavljen udar. Prvi primer: 12 štete približno na 10 sekundi.')}${card('Dva dobra odgovora','Štit ublažava pogodak. Prekid otkazuje najavu i otvara prostor za novu reč.')}<p class="mini-label">Probne vrednosti, za proveru u prototipu.</p>${btn('Pripremi susret','encounter')}</div>`;
 case 'challenge':return `${gameTop('Izazov reči','home')}<div class="content center"><div class="large-symbol">✦</div><span class="section-kicker">OPCIONA VEŽBA</span><h2>Jedna tabla.<br>Mnogo puteva.</h2>${card('Duga reč','Pronađi reč od najmanje 5 slova. Bez neprijateljskog sata i bez rang-liste.')}<p class="lead">Izazovi su kasniji predlog. Sada možeš pregledati mirnu probu osnovnog unosa.</p>${btn('Otvori trening','training')}</div>`;
 case 'cosmetics':return `${gameTop('Tvoj svetionik','home')}<div class="content"><h2>Neka svetli<br>na tvoj način.</h2><div class="landscape">${scenery()}</div>${row('✧','Prva svetlost','Trenutni izgled · početni','cosmetic-detail')}${row('☾','Mesečev vrt','Završi Svetlucavi gaj','cosmetic-detail')}${row('◇','Stakleni cvetovi','Otkrij oblast 02','region-locked')}<p class="mini-label">Samo izgled · bez borbenih bonusa.</p></div>`;
 case 'cosmetic-detail':return `${gameTop('Mesečev vrt','cosmetics')}<div class="content center"><div class="landscape">${scenery()}</div><h2>Vrt koji cveta<br>kad svet utihne.</h2><span class="pill gold">NAGRADA KAMPANJE</span><p class="lead" style="margin:20px 0">Otključava se završetkom Svetlucavog gaja. Koncept kozmetike, bez uticaja na snagu.</p>${btn('Vrati se na izgled svetionika','cosmetics')}${btn('Nastavi ekspediciju','map','')}</div>`;
 case 'settings':return `${gameTop('Podešavanja',settingsReturn)}<div class="content">${[['Muzika','Bez zvuka u mockupu'],['Efekti','Bez zvuka u mockupu'],['Vibracija','Primer kontrole']].map(([n,t])=>`<label class="settings-line"><span>${n}<small>${t}</small><input class="toggle" type="checkbox" checked></label>`).join('')}${row('Aa','Pristupačnost','Tekst, kontrast, kretanje','accessibility')}${row('A','Jezik i rečnik','Srpski · latinica','language')}${row('☁','Profil i čuvanje','Lokalni napredak','save')}${row('?','Pomoć i pravila','Uputstvo, povratna informacija','help')}${row('i','O igri','Autori i materijali','credits')}${btn('Nazad',settingsReturn,'')}</div>`;
 case 'accessibility':return `${gameTop('Pristupačnost','settings')}<div class="content"><h2>Tvoj način<br>da čuješ svet.</h2>${[['large-text','Veći tekst','Uvećava tekst u ovom pregledu.'],['high-contrast','Pojačan kontrast','Zadržava tekst i simbole uz boju.'],['reduced-motion','Manje kretanja','Bez treperenja i ponavljanih efekata.']].map(([id,n,t])=>`<label class="settings-line"><span>${n}<small>${t}</small><input class="toggle" type="checkbox" data-setting="${id}" ${document.body.classList.contains(id)?'checked':''}></label>`).join('')}${card('Unos dodirom ili tastaturom','U atlasu uvek možeš dodirivati krugove redom i izabrati Potvrdi. Tastatura: Tab i Enter; Escape briše trenutni unos.')}${btn('Isprobaj u treningu','training')}</div>`;
 case 'dictionary':return `${gameTop('Pravila reči','help')}<div class="content"><h2>Sloboda reči.<br>Jasna pravila.</h2>${card('Najmanje 3 slova','Jedan krug jednom po reči. Za dva ista slova potrebna su dva kruga.')}${card('Ista reč, jednom po skupu','Mešanje menja raspored, ne pamćenje prihvaćenih reči.')}${card('Dijakritika je važna','C, Č i Ć nisu isto slovo. Jezički paketi traže posebne pregledane table.')}<p class="mini-label">Demo lista: MOST, MAST, MIR, RAT, SAT, MORA, STO, TRI, TAMA, RAM, RAST, STAR, KRASTI, RASTI, RANI, RAN, RAK, SAN, STAN, TRN, SIT, SIR, SIN. Nije produkcioni rečnik.</p>${btn('Nedostaje reč?','word-report','')}</div>`;
 case 'word-report':return `${gameTop('Predloži reč','dictionary')}<div class="content"><h2>Možda rečnik<br>nešto ne čuje.</h2><p class="lead">Predlog ide na pregled. Ne menja bodove u borbi.</p><label class="field-label">Reč<input class="game-input" id="reported-word" maxlength="40" placeholder="Upiši reč"></label><label class="field-label">Kratko značenje<textarea class="game-input" rows="3" maxlength="300" placeholder="Kako koristiš ovu reč?"></textarea></label><p class="mini-label">Prikaz formulara · nema slanja ni trajnog čuvanja.</p>${act('Pregledaj lokalnu belešku','report')}</div>`;
 case 'save':return `${gameTop('Profil i čuvanje','settings')}<div class="content">${creature('mint')}<h2>Luka, istraživač.</h2><span class="pill">LOKALNI PROFIL · PRIMER</span>${card('Na ovom uređaju','Oblast 02 · 18 susreta · poslednji upis danas, 18:42.')}${card('Čuvanje u oblaku','Buduća opcija. Nije povezano ni implementirano.',btn('Pregled offline stanja','cloud-offline',''))}${btn('Pregled konflikta napretka','save-conflict','')}${btn('Obriši lokalni profil','reset-confirm','ghost')}</div>`;
 case 'help':return `${gameTop('Tu smo da razjasnimo','settings')}<div class="content"><h2>Gde je zapelo?</h2>${row('A','Kako se sastavlja reč?','Pravila slova i prihvatanja','dictionary')}${row('⚡','Kako rade sposobnosti?','Ponovi kratko uputstvo','tutorial-energy')}${row('↻','Ponovi prvi korak','Bez gubitka napretka','tutorial-word')}${row('✎','Prijavi problem','Pregled lokalnog formulara','feedback')}${row('i','O projektu','Poreklo i status materijala','credits')}</div>`;
 case 'feedback':return `${gameTop('Beleška o problemu','help')}<div class="content"><h2>Pomozi nam<br>da bolje čujemo.</h2><label class="field-label">Šta se dogodilo?<select class="game-select"><option>Problem sa unosom</option><option>Prikaz ekrana</option><option>Napredak nije sačuvan</option><option>Drugo</option></select></label><label class="field-label">Opis<textarea id="feedback-text" class="game-input" rows="5" maxlength="1000" placeholder="Opiši korake koji su doveli do problema."></textarea></label><p class="mini-label">Ništa se ne šalje. Lični podaci i stvarni logovi nisu uključeni.</p>${act('Pregledaj belešku','feedback')}</div>`;
 case 'credits':return `${gameTop('War of Words','help')}<div class="content"><span class="section-kicker">RADNI NAZIV · KONCEPT 01</span><h2>Svet koji<br>tek dobija glas.</h2>${card('Vizuelni materijal','Originalne programski nacrtane vektorske ilustracije i interfejs, izrađeni za ovaj projekat. Bez preuzetih grafičkih paketa.')}${card('Rečnik','Mala ručno upisana demo lista. Produkcioni izvor, verzija i licenca još nisu izabrani.')}${card('Status','Mockup ekrana. Engine, konačna tema, balans i monetizacija nisu usvojeni.')}<p class="mini-label">Tehničke licence repozitorijuma dokumentovane su odvojeno u docs/third-party.md.</p></div>`;
 case 'reset':return `${gameTop('Brisanje lokalnog profila','save')}<div class="content"><span class="pill red">NEPOVRATNA RADNJA U BUDUĆOJ IGRI</span><h2>Početi<br>sasvim iznova?</h2><p class="lead">Ovo bi obrisalo kampanju, kolekciju i podešavanja lokalnog profila. U atlasu se ne brišu stvarni podaci.</p><label class="field-label">Za prikaz potvrde upiši OBRIŠI<input id="reset-text" class="game-input" autocomplete="off"></label>${btn('Sačuvaj profil i vrati se','save')}${act('Simuliraj brisanje','reset','danger')}</div>`;
 case 'loading':return `<div class="content center" style="padding-top:55px"><span class="section-kicker">SVETLUCAVI GAJ</span><div class="landscape">${scenery()}</div><h2>Pratimo trag<br>tvog glasa.</h2><div class="meter" role="progressbar" aria-valuenow="68" aria-valuemin="0" aria-valuemax="100" aria-label="Ilustrativni napredak učitavanja"><i style="width:68%"></i></div><p class="mini-label" style="margin-top:12px">Priprema oblasti · primer 68%</p>${card('Mali podsetnik','Duže reči daju više energije. Ali kratka reč u pravom trenutku može spasiti susret.')}${btn('Nastavi pregled','encounter')}</div>`;
 case 'save-conflict':return `${gameTop('Koju priču nastavljaš?','save')}<div class="content"><h2>Dva traga.<br>Jedno putovanje.</h2><p class="lead">Pregledaj oba pre izbora. Nijedan se ovde automatski ne prepisuje.</p>${card('Ovaj uređaj','Danas, 18:42 · oblast 02 · 18 susreta',btn('Izaberi ovaj uređaj','save-choice'))}${card('Drugi uređaj','Juče, 21:10 · oblast 01 · 12 susreta',act('Pregledaj stariji trag','older-save',''))}${btn('Odustani od izbora','save','ghost')}</div>`;
 default:return `<div class="content"><h2>${s.title}</h2>${btn('Nazad u bazu','home')}</div>`;
}}

function list(){let n=0;$('#count').textContent=SCREENS.length;$('#screen-list').innerHTML=GROUPS.map(g=>{const all=SCREENS.filter(s=>s.group===g);const matches=all.filter(s=>(s.title+' '+s.why+' '+s.scope).toLocaleLowerCase('sr').includes(filter));return matches.length?`<section class="screen-group"><div class="group-title">${g}<span>${matches.length}</span></div>${matches.map(s=>`<button class="screen-link ${s.id===current?'active':''}" data-go="${s.id}" ${s.id===current?'aria-current="page"':''}><span>${String(SCREENS.indexOf(s)+1).padStart(2,'0')}</span>${s.title}</button>`).join('')}</section>`:''}).join('')||'<p class="empty-search">Nema rezultata. Pokušaj „reč“, „borba“ ili „čuvanje“.</p>';}
function inspector(s){$('#inspector').innerHTML=`<div class="inspector-box"><span class="number-label">${String(SCREENS.indexOf(s)+1).padStart(2,'0')} / ${SCREENS.length}</span><h2>${s.title}</h2><span class="scope-tag">${s.scope} · predlog</span><p>${s.why}</p></div><div class="inspector-box"><h3>NASTAVI ISTRAŽIVANJE</h3>${s.links.map(id=>`<button class="route" data-go="${id}">${byId(id).title}<span>↗</span></button>`).join('')}</div><div class="inspector-box"><h3>DIZAJNERSKE GRANICE</h3><ul class="note-list"><li>Ilustrativni podaci i zamrznut borbeni sat.</li><li>Bez naloga, plaćanja i mrežnih servisa.</li><li>Engine, svet i konačan rečnik ostaju otvoreni.</li><li>Atlas služi odluci šta ulazi u prvi prototip.</li></ul></div>`}
function resetDemo(s){demo={energy:s.data.energy??13,hp:s.data.hp??76,enemy:64,used:[],chosen:s.data.selected?[...s.data.selected]:[],letters:s.data.board?[...s.data.board]:['M','O','S','T','A','R','I'],shield:!!s.data.shield,sets:0,training:false};}
function draw(){const s=byId(current);list();document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);b.setAttribute('aria-pressed',String(b.dataset.view===view));});$('#studio').classList.toggle('atlas-mode',view!=='play');if(view==='play'){resetDemo(s);$('#workspace').innerHTML=`<div class="stage-head"><div><h1>${s.title}</h1><p>${s.group} / ${s.scope}</p></div><div class="stage-nav"><button class="small-btn" data-action="prev" aria-label="Prethodni ekran">←</button><button class="small-btn" data-action="next" aria-label="Sledeći ekran">→</button></div></div><div class="phone-wrap">${phone(s)}</div><p class="stage-caption">Interaktivni dizajn · osnovni okvir 366 × 758<br>Izaberi ekran levo ili prati dugmad u igri.</p>`;inspector(s);const modal=$('#workspace .modal');if(modal){const screen=$('#workspace .screen');[...screen.children].filter(c=>!c.classList.contains('modal-shade')).forEach(c=>{c.inert=true;});}}else if(view==='atlas'){const matches=SCREENS.filter(s=>(s.title+' '+s.why+' '+s.scope).toLocaleLowerCase('sr').includes(filter));$('#workspace').innerHTML=`<div class="stage-head"><div><h1>Atlas svih ekrana</h1><p>${matches.length} prikaza · dodirni karticu za interaktivni pregled</p></div></div><div class="atlas-grid">${matches.map(s=>`<section class="atlas-item"><div class="atlas-preview" data-open="${s.id}">${phone(s)}</div><h2><button class="small-btn" data-go="${s.id}">${String(SCREENS.indexOf(s)+1).padStart(2,'0')} · ${s.title}</button></h2><p>${s.group} · ${s.scope}</p></section>`).join('')}</div>`;$('#workspace').querySelectorAll('.atlas-preview .phone').forEach(p=>{p.inert=true;p.setAttribute('aria-hidden','true');p.parentElement.style.height=Math.ceil(p.getBoundingClientRect().height+2)+'px'});}else{$('#workspace').innerHTML=`<div class="stage-head"><div><h1>Kako se ekrani povezuju</h1><p>Osam puteva kroz igru · svaki korak otvara mockup</p></div></div><div class="flow-lanes">${FLOWS.map(([title,text,ids])=>`<section class="flow-lane"><h2>${title}</h2><p>${text}</p><div class="flow-chain">${ids.map((id,i)=>`${i?'<span>→</span>':''}<button data-go="${id}">${byId(id).title}</button>`).join('')}</div></section>`).join('')}</div>`;}$('#announcement').textContent=s.title;}
let battleMemory=null;
function go(id){const old=current;if(current==='battle'&&id==='pause')battleMemory=structuredClone(demo);if(!byId(id))return;if(id==='settings')settingsReturn=['pause','battle'].includes(current)?'pause':'home';current=id;view='play';history.replaceState(null,'','#'+id);draw();if(id==='battle'&&['pause','resume'].includes(old)&&battleMemory){demo=structuredClone(battleMemory);document.querySelectorAll('#workspace [data-letter]').forEach((b,i)=>{b.textContent=demo.letters[i];b.setAttribute('aria-label','Slovo '+demo.letters[i])});refreshEnergy();updateBoard();$('#workspace #enemy-value').textContent=demo.enemy+'/80';$('#workspace #enemy-bar').style.width=(demo.enemy/80*100)+'%';$('#workspace #set-count').textContent=demo.used.length+'/3 reči → nova slova';message('Borba nastavljena · stanje je sačuvano.');}}
function message(text,error=false){const el=$('#workspace #word-message');if(el){el.textContent=text;el.classList.toggle('error',error);}$('#announcement').textContent=text;}
function updateBoard(){const word=demo.chosen.map(i=>demo.letters[i]).join('');const el=$('#workspace #word-value');if(el)el.textContent=word||'· · ·';document.querySelectorAll('#workspace [data-letter]').forEach(b=>b.classList.toggle('selected',demo.chosen.includes(Number(b.dataset.letter))));const line=$('#workspace .letter-line polyline');if(line)line.setAttribute('points',demo.chosen.map(i=>`${positions[i][0]+25.5},${positions[i][1]+25.5}`).join(' '));}
function selectLetter(i){if(demo.chosen.at(-2)===i)demo.chosen.pop();else if(!demo.chosen.includes(i))demo.chosen.push(i);updateBoard();}
function refreshEnergy(){const el=$('#workspace #energy-value');if(el)el.textContent=demo.energy+'/30';}
const words=new Set('MOST MAST MIR RAT SAT MORA STO TRI TAMA RAM RAST STAR KRASTI RASTI RANI RAN RAK SAN STAN TRN SIT SIR SIN'.split(' '));
function nextSet(){demo.letters=demo.sets%2?['M','O','S','T','A','R','I']:['R','A','N','I','K','S','T'];demo.sets++;demo.used=[];demo.chosen=[];document.querySelectorAll('#workspace [data-letter]').forEach((b,i)=>{b.textContent=demo.letters[i];b.setAttribute('aria-label','Slovo '+demo.letters[i])});updateBoard();const count=$('#workspace #set-count');if(count)count.textContent='0/3 reči → nova slova';}
function submit(){const word=demo.chosen.map(i=>demo.letters[i]).join('');if(demo.chosen.length<3){message('Potrebna su najmanje 3 slova.',true);demo.chosen=[];return;}if(!words.has(word)){message('Nema u demo rečniku. Pokušaj MOST, MAST ili RAT.',true);demo.chosen=[];return;}if(demo.used.includes(word)){message(word+' je već dao energiju u ovom skupu.',true);demo.chosen=[];return;}const gain=({3:3,4:5,5:8,6:12,7:17})[demo.chosen.length]||3;const added=Math.min(gain,30-demo.energy);demo.energy+=added;demo.used.push(word);demo.chosen=[];refreshEnergy();message(`${word} · +${added} energije${added<gain?' · kapacitet 30':''} · ${demo.used.length}/3 reči`);const count=$('#workspace #set-count');if(count)count.textContent=demo.used.length+'/3 reči → nova slova';if(demo.used.length===3){nextSet();message(`${word} · +${added} energije · novi skup je spreman.`);}}
function action(name){if(name==='next'||name==='prev'){go(SCREENS[(SCREENS.findIndex(s=>s.id===current)+(name==='next'?1:SCREENS.length-1))%SCREENS.length].id);return;}if(name==='submit'){submit();return;}if(name==='shuffle'){demo.chosen=[];demo.letters=[...demo.letters.slice(2),...demo.letters.slice(0,2)];document.querySelectorAll('#workspace [data-letter]').forEach((b,i)=>{b.textContent=demo.letters[i];b.setAttribute('aria-label','Slovo '+demo.letters[i])});updateBoard();message('Raspored je izmešan. Iskorišćene reči ostaju upamćene.');return;}if(name==='replace'){nextSet();message('Novi skup · ručna zamena bez tajmera u atlasu.');return;}if(['hit','shield','interrupt'].includes(name)){if(!$('#workspace #energy-value'))return;const cost={hit:6,shield:5,interrupt:10}[name];if(current==='interrupt'&&name==='interrupt'){message('Prekid se oporavlja · ilustrativnih 15 s.',true);return;}if(demo.energy<cost){message(`Nedostaje još ${cost-demo.energy} energije.`,true);return;}if(name==='shield'&&demo.shield){message('Štit je već aktivan; zaštita se ne sabira.');return;}demo.energy-=cost;refreshEnergy();if(name==='hit'){demo.enemy=Math.max(0,demo.enemy-10);$('#workspace #enemy-value').textContent=demo.enemy+'/80';$('#workspace #enemy-bar').style.width=(demo.enemy/80*100)+'%';message('Udarac · −10 zdravlja protivnika.');if(demo.enemy===0)go(demo.training?'training-results':'victory');}else if(name==='shield'){demo.shield=true;message('Štit aktivan · naredni pogodak ublažen za 8.');}else{message('Najavljeni napad je prekinut. Sat je zamrznut u mockupu.');}return;}if(name==='profile-next'){const input=$('#player-name');if(!input.value.trim()){input.setCustomValidity('Upiši ime istraživača.');input.reportValidity();input.oninput=()=>input.setCustomValidity('');return;}go('intro');return;}if(name==='report'||name==='feedback'){const input=$(name==='report'?'#reported-word':'#feedback-text');if(!input.value.trim()){input.setCustomValidity('Popuni ovo polje za pregled beleške.');input.reportValidity();input.oninput=()=>input.setCustomValidity('');return;}go(name==='report'?'report-saved':'feedback-saved');return;}if(name==='reset'){const input=$('#reset-text');if(input.value.trim().toLocaleUpperCase('sr')!=='OBRIŠI'){input.setCustomValidity('Za simulaciju upiši OBRIŠI.');input.reportValidity();input.oninput=()=>input.setCustomValidity('');return;}go('profile');return;}if(name==='training'){go('battle');demo.training=true;$('#workspace .attack-warning').innerHTML='<span>VEŽBA · BEZ PROTIVNIČKOG SATA</span>';message('Trening · reči i sposobnosti bez pritiska.');return;}if(name==='older-save'){go('save-choice');$('#workspace .modal p').textContent='Izabran: drugi uređaj, oblast 1, 12 susreta. U pravoj igri druga verzija mora biti sačuvana kao rezerva. Ovo je simulacija.';}}
document.addEventListener('click',e=>{const el=e.target.closest('[data-go],[data-action],[data-view],[data-open]');if(el){if(el.dataset.go)go(el.dataset.go);else if(el.dataset.open)go(el.dataset.open);else if(el.dataset.view){view=el.dataset.view;draw();}else action(el.dataset.action);return;}const letter=e.target.closest('[data-letter]');if(letter&&e.detail===0)selectLetter(Number(letter.dataset.letter));});
$('#search').addEventListener('input',e=>{filter=e.target.value.toLocaleLowerCase('sr');if(view==='atlas')draw();else list();});
document.addEventListener('change',e=>{if(e.target.dataset.setting)document.body.classList.toggle(e.target.dataset.setting,e.target.checked);});
window.addEventListener('hashchange',()=>{if(byId(location.hash.slice(1)))go(location.hash.slice(1));});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#workspace .letters')){demo.chosen=[];updateBoard();message('Unos otkazan.');}});
let drag=null;
document.addEventListener('pointerdown',e=>{const letter=e.target.closest('#workspace [data-letter]');if(!letter||view!=='play'||e.button!==0)return;const board=letter.closest('.letters');drag={id:e.pointerId,board,start:Number(letter.dataset.letter),moved:false,lastX:e.clientX,lastY:e.clientY};selectLetter(drag.start);board.setPointerCapture(e.pointerId);e.preventDefault();});
document.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;const r=drag.board.getBoundingClientRect();const dx=e.clientX-drag.lastX,dy=e.clientY-drag.lastY,steps=Math.ceil(Math.hypot(dx,dy)/9);for(let k=1;k<=steps;k++){const x=drag.lastX+dx*k/steps-r.left,y=drag.lastY+dy*k/steps-r.top;const i=positions.findIndex(([px,py])=>Math.hypot(x-px-25.5,y-py-25.5)<26);if(i>=0&&i!==demo.chosen.at(-1)){drag.moved=true;selectLetter(i);}}drag.lastX=e.clientX;drag.lastY=e.clientY;});
document.addEventListener('pointerup',e=>{if(!drag||drag.id!==e.pointerId)return;const moved=drag.moved;drag=null;if(moved)submit();});
document.addEventListener('pointercancel',()=>{if(drag){drag=null;demo.chosen=[];updateBoard();message('Dodir je prekinut. Reč nije poslata.');}});
draw();
