/* Svi nazivi, brojke i prošireni sistemi u ovom atlasu su predlozi. */
const GROUPS = ['Prvi susret','Baza i ekspedicija','Borba','Ishod i napredovanje','Kolekcija i radionica','Dodatni sadržaji','Podešavanja','Prekidi i oporavak'];
const SCREENS = [];
function S(id,group,title,kind,data,why,links,scope='Osnovni tok') { SCREENS.push({id,group:GROUPS[group],title,kind,data,why,links,scope}); }
S('splash',0,'Naslovni ekran','splash',{},'Prvi utisak: reči bude svet koji je utihnuo. Jedna jasna akcija vodi u igru.',['language','home']);
S('language',0,'Jezik i pismo','language',{},'Odvojiti jezik interfejsa od rečnika. Izbor paketa menja i skupove slova; nije samo prevod.',['profile','dictionary']);
S('profile',0,'Novi istraživač','profile',{},'Lokalni profil bez obavezne registracije. Ime može kasnije da se promeni.',['intro','save']);
S('intro',0,'Prolog: svet bez glasa','story',{speaker:'NIMA · ČUVARKA SVETIONIKA',heading:'Ostrva su zaboravila svoja imena.',text:'Ali čujem nešto u tebi. Izgovori prvu reč — možda nas svet ponovo čuje.',next:'tutorial-word'},'Kratka priča sa opcijom preskakanja. Lik i tematika su autorski koncept.',['tutorial-word','home']);
S('tutorial-word',0,'Uvod: sastavi reč','tutorial',{step:1,heading:'Svaka reč je iskra.',text:'Poveži M → O → S → T, pa pusti prst. Možeš i da dodiruješ slova redom.',next:'tutorial-energy'},'Učenje jedne radnje bez neprijateljskog sata. Ista tabla kao u borbi.',['tutorial-energy','battle']);
S('tutorial-energy',0,'Uvod: energija i sposobnosti','tutorial',{step:2,heading:'Reč postaje energija.',text:'MOST daje 5 energije. Udarac košta 6, a štit 5. Sačuvaj energiju ili se zaštiti.',next:'tutorial-defense'},'Razdvojiti uspeh pri sastavljanju reči od ručnog aktiviranja napada.',['tutorial-defense','battle']);
S('tutorial-defense',0,'Uvod: pročitaj protivnika','tutorial',{step:3,heading:'Vidi napad pre nego što stigne.',text:'Protivnik priprema udar. Štit ublažava pogodak; prekid otkazuje najavljeni napad.',next:'home'},'Vežba bez kazne. Prvi obavezni susret se ne ubrzava usred objašnjenja.',['home','battle']);
S('home',1,'Baza: svetionik','home',{},'Centralno mesto za nastavak ekspedicije. Kolekcija i radionica su sporedni putevi, a sledeća borba je glavni poziv.',['map','team','quests','settings']);
S('map',1,'Mapa oblasti','map',{},'Kratka čitljiva staza, osvojeni susreti, jedan aktivan korak i vidljiv boss. Bez zatrpavanja mapom celog sveta.',['encounter','region-locked','world']);
S('world',1,'Atlas ostrva','world',{},'Širi svet sa jasnom razlikom između dostupnog, otkrivenog i nepoznatog.',['map','region-locked','chapter-end'],'Proširenje');
S('region-locked',1,'Zaključana oblast','modal',{base:'map',symbol:'◇',heading:'Magla još ne popušta.',text:'Pobedi Čuvara tišine u Svetlucavom gaju da otvoriš put ka Staklenim plićacima.',primary:['Nazad na stazu','map']},'Objasniti uslov otključavanja i vratiti igrača na ostvariv zadatak.',['map','boss-intro']);
S('encounter',1,'Priprema susreta','encounter',{},'Pre ulaska prikazati obrazac neprijatelja, garantovanu prvu nagradu i izabrane sposobnosti.',['team','battle','map']);
S('team',1,'Izbor tri sposobnosti','team',{},'Tri uloge: napad, odbrana, kontrola. Igrač zna cenu pre borbe.',['encounter','ability','collection']);
S('dialogue',1,'Susret na putu','story',{speaker:'NIMA · OSLUŠKUJE GAJ',heading:'Ovo nije obična tišina.',text:'Sakuplja se oko starog korena. Kad zasvetli oklop čuvara, sačuvaj energiju za prekid.',next:'boss-intro'},'Priča prenosi i taktički trag. Preskakanje ne skriva pravilo borbe.',['boss-intro','map'],'Proširenje');
S('battle',2,'Borba: spreman potez','battle',{},'Gore borba, u sredini energija i tri sposobnosti, dole stabilna tabla sa sedam krugova. Prevuci ili koristi dodir/klik pa Potvrdi.',['word-ok','enemy-warning','pause','victory'],'Prototip');
S('word-drag',2,'Borba: povezivanje slova','battle',{word:'MOST',selected:[0,1,2,3],message:'Pusti prst da potvrdiš · nazad briše slovo'},'Aktivna putanja i reč stoje iznad prsta. Ukrštanje putanja je dozvoljeno. Tabla se ne menja tokom dodira.',['word-ok','touch-cancel'],'Prototip');
S('word-ok',2,'Prihvaćena reč','battle',{word:'MOST',energy:18,message:'+5 energije · 2/3 reči u ovom skupu'},'Potvrda povezuje reč i resurs. Nema dodatne valute za svaku sposobnost.',['battle','board-refresh'],'Prototip');
S('word-invalid',2,'Reč nije u rečniku','battle',{word:'MTS',message:'Nema u rečniku · pokušaj ponovo',error:true},'Bez gubitka energije ili zdravlja zbog odbijene reči. Razlikovati nepostojeću, prekratku i ponovljenu reč.',['word-short','word-repeat','word-report'],'Prototip');
S('word-short',2,'Prekratka reč','battle',{word:'MO',message:'Potrebna su najmanje 3 slova.',error:true},'Precizna lokalna povratna informacija; igrač ne mora da otvara pravila.',['battle','word-invalid'],'Prototip');
S('word-repeat',2,'Već iskorišćena reč','battle',{word:'MOST',message:'MOST je već doneo energiju u ovom skupu.',error:true},'Mešanje rasporeda ne resetuje iskorišćene reči. Novi skup ponovo dozvoljava istu reč.',['board-refresh','battle'],'Prototip');
S('energy-low',2,'Nedovoljno energije','battle',{energy:3,message:'Za udarac nedostaje još 3 energije.'},'Trošak ostaje vidljiv; tap na nedostupnu sposobnost objašnjava koliko nedostaje.',['word-ok','battle'],'Prototip');
S('energy-full',2,'Puna energija','battle',{energy:30,message:'Energija je puna · iskoristi sposobnost.'},'Jasno pokazati gornju granicu; prihvaćena reč se i dalje beleži. Bez nove kazne za dobro igranje.',['ability-cast','battle'],'Prototip');
S('enemy-warning',2,'Najava snažnog napada','battle',{warning:'SNAŽAN UDAR · 3 s',message:'Štit ili prekid? Ti biraš odgovor.'},'Opasnost ima tekst i simbol, ne samo crvenu boju. Najava ne prekriva tablu.',['shield','interrupt','low-health'],'Prototip');
S('ability-cast',2,'Aktiviran napad','battle',{energy:7,effect:'−10',message:'Iskra pogađa · potrošeno 6 energije.'},'Efekat je u borbenoj zoni; slova i aktuelni unos ostaju stabilni.',['battle','victory'],'Prototip');
S('shield',2,'Aktivan štit','battle',{energy:8,shield:true,message:'Štit spreman · sledeći pogodak je ublažen.'},'Trajanje/okidanje zaštite mora biti jasno. Štit se ne sabira sa samim sobom.',['battle','enemy-warning'],'Prototip');
S('interrupt',2,'Prekid i oporavak sposobnosti','battle',{energy:3,warning:'NAPAD PREKINUT',message:'Prekid ponovo dostupan za 15 s.',cooldown:true},'Razlikovati cooldown od nedostatka energije. Ovaj atlas zamrzava vreme radi pregleda.',['battle','energy-low'],'Prototip');
S('board-refresh',2,'Novi skup slova','battle',{word:'NOVI SKUP',message:'3/3 reči · novi skup je spreman.',board:['R','A','N','I','K','S','T']},'Zamena samo posle puštanja. Kratko zaustaviti borbeni sat dok se tabla menja; automatska popravka lošeg skupa je besplatna.',['battle','board-empty'],'Prototip');
S('board-empty',2,'Skup bez preostalih rešenja','modal',{base:'battle',symbol:'↻',heading:'Vreme je za nova slova.',text:'Ovaj skup nema dovoljno novih reči. Dobijaš novi skup bez troška; borba miruje tokom zamene.',primary:['Nastavi sa novim skupom','board-refresh']},'Rezervna putanja za iscrpljen ili neispravno pripremljen skup. U igri se može svesti na kratak banner.',['board-refresh'],'Prototip');
S('low-health',2,'Kritično zdravlje','battle',{hp:12,warning:'SLEDEĆI UDAR MOŽE BITI POSLEDNJI',message:'12/100 zdravlja · štit je dostupan.'},'Jasna brojka i taktički savet bez treperenja, pomeranja table ili kažnjavanja sporijeg čitanja.',['shield','defeat','pause'],'Prototip');
S('boss-intro',2,'Ulazak bossa','boss',{},'Velika silueta i jedna razumljiva mehanika. Uvod može da se preskoči pri ponovnom pokušaju.',['boss-phase','battle','map'],'Proširenje');
S('boss-phase',2,'Boss: promena faze','battle',{boss:true,warning:'FAZA II · PUKOTINA U OKLOPU',message:'Priprema dva udara · prekid zaustavlja oba.'},'Promena obrasca je unapred najavljena, sa najmanje dva moguća odgovora. Brojke i pravilo su predlog.',['interrupt','shield','victory'],'Proširenje');
S('pause',2,'Pauza','modal',{base:'battle',symbol:'Ⅱ',heading:'Udahni.',text:'Borba je zaustavljena. Tvoja reč i raspored slova ostaju sačuvani.',primary:['Nastavi borbu','battle'],secondary:['Podešavanja','settings'],tertiary:['Napusti susret','quit']},'Pauza ne troši resurse. Vraćanje ne pokreće neprijateljski napad pre nego što je ekran spreman.',['battle','settings','quit'],'Prototip');
S('quit',2,'Potvrda napuštanja','modal',{base:'battle',symbol:'↩',heading:'Nazad u svetionik?',text:'Napredak ove borbe neće biti sačuvan. Ranije osvojene nagrade ostaju tvoje.',primary:['Ostani u borbi','battle'],secondary:['Napusti susret','home']},'Nedestruktivna opcija je dominantna. Jasno razlikovati borbeni napredak od kolekcije.',['battle','home'],'Prototip');
S('victory',3,'Pobeda','victory',{},'Pokazati ishod, konkretne nagrade i jednu zanimljivu ličnu statistiku. Zvezdice su opciona proširena ocena.',['reward','battle-summary','map'],'Prototip');
S('defeat',3,'Poraz i novi pokušaj','defeat',{},'Jedan koristan savet vezan za obrazac, brz novi pokušaj. Bez plaćenog oživljavanja u predlogu.',['battle','team','map'],'Prototip');
S('battle-summary',3,'Pregled borbe','summary',{},'Pregled reči, potrošnje energije i odbrane; pomoći učenju umesto zatrpavanja tabelama.',['word-report','reward','map']);
S('reward',3,'Preuzimanje nagrade','reward',{},'Garantovana nagrada prve pobede. Otkrivanje nije nasumična kupovina.',['new-echo','upgrade-choice','map']);
S('new-echo',3,'Nova sposobnost otključana','unlock',{},'Pokazati šta novi odjek radi i gde ulazi u tim. Bez obaveznog automatskog opremanja.',['team','ability','map'],'Proširenje');
S('upgrade-choice',3,'Izbor taktičke nadogradnje','choice',{},'Dve grane menjaju odluku u borbi. Igrač vidi posledicu pre potvrđivanja.',['upgrade-confirm','upgrade-strong-confirm']);
S('upgrade-confirm',3,'Potvrda grane','modal',{base:'ability',symbol:'◇',heading:'Štit koji vraća iskru',text:'Pravovremeni štit vraća 2 energije. Izbor menja granu ove sposobnosti; poništavanje grane još nije dogovoreno.',primary:['Izaberi povraćaj energije','upgrade-return-done'],secondary:['Uporedi ponovo','upgrade-choice']},'Ako je odluka trajna, potvrda mora opisati tu posledicu. Respec ostaje otvorena odluka.',['upgrade-choice','upgrade-done']);
S('chapter-end',3,'Oblast oslobođena','chapter',{},'Emotivni predah: svet vizuelno vraća glas, mapa otkriva novu oblast.',['world','home'],'Proširenje');
S('collection',4,'Kolekcija odjeka','collection',{},'Vidljive uloge i opremljenost. Zaključane siluete bude radoznalost uz konkretan uslov.',['ability','collection-locked','collection-empty','team'],'Proširenje');
S('ability',4,'Detalj sposobnosti','ability',{},'Efekat, cena, grana i izvor unapređenja na jednom mestu. Brojke su primer, ne usvojen balans.',['team','upgrade-choice','upgrade-cost'],'Proširenje');
S('collection-locked',4,'Neotkriveni odjek','detail-locked',{},'Silhueta i mesto pronalaska, bez cene ili slučajne kupovine.',['map','collection'],'Proširenje');
S('collection-empty',4,'Prazna kolekcija / filter','empty',{symbol:'◇',heading:'Još nijedan odjek ovde.',text:'U ovom izboru nema odjeka. Prvi odjek kontrole čeka na kraju Svetlucavog gaja.',primary:['Prikaži sve odjeke','collection'],secondary:['Idi na mapu','map']},'Prazan rezultat nije greška: objasniti razlog i ponuditi izlaz ili sledeći korak.',['collection','map'],'Proširenje');
S('workshop',4,'Radionica','workshop',{},'Mesto za namerna unapređenja. Jedan materijal van borbe, odvojen od privremene borbene energije.',['upgrade-cost','ability','inventory'],'Proširenje');
S('upgrade-cost',4,'Pregled troška nadogradnje','upgrade-cost',{},'Uporediti sada i posle, prikazati stvarno stanje materijala. Sve vrednosti su mock podaci.',['upgrade-done','materials-low'],'Proširenje');
S('materials-low',4,'Nedostaje materijal','modal',{base:'workshop',symbol:'◈',heading:'Još 40 svetlopraha.',text:'Imaš 80 od potrebnih 120. Svetloprah dobijaš završavanjem susreta u Svetlucavom gaju.',primary:['Pronađi susret','map'],secondary:['Nazad u radionicu','workshop']},'Igraču pokazati put do resursa u igri. Monetizacija nije odlučena niti ugrađena u ovaj tok.',['map','workshop'],'Proširenje');
S('upgrade-done',4,'Nadogradnja završena','upgrade-done',{},'Povratna informacija poredi staro i novo i odmah vodi ka upotrebi.',['team','map'],'Proširenje');
S('inventory',4,'Ranac i predmeti','inventory',{},'Materijali i predmeti imaju izvor i svrhu. Bez lažne hitnosti i nepotrebne granice kapaciteta.',['workshop','item-detail'],'Proširenje');
S('item-detail',4,'Detalj predmeta','item',{},'Objasniti gde se predmet dobija i čemu služi; primarna radnja vodi na relevantno mesto.',['workshop','inventory'],'Proširenje');
S('quests',5,'Zadaci ekspedicije','quests',{},'Stalni ciljevi umesto obaveznog dnevnog dolaska. Nema gubitka niza ako se preskoči dan.',['quest-reward','map','quests-empty'],'Opciono');
S('quest-reward',5,'Zadatak završen','modal',{base:'quests',symbol:'✧',heading:'Reči grade mostove.',text:'Sastavio si 10 različitih reči. Nagrada: 40 svetlopraha.',primary:['Preuzmi nagradu','quests-empty']},'Preuzimanje treba da bude jednokratno i pouzdano. Atlas samo prikazuje stanje, ne vodi trajnu ekonomiju.',['quests-empty','workshop'],'Opciono');
S('quests-empty',5,'Svi zadaci završeni','empty',{symbol:'✓',heading:'Sve zaokruženo.',text:'Ciljevi ove oblasti su završeni. Nova otkrića čekaju u sledećoj oblasti.',primary:['Nastavi putovanje','world'],secondary:['Slobodan trening','training']},'Prazno stanje priznaje završetak, bez nagovaranja na kupovinu ili čekanje.',['world','training'],'Opciono');
S('training',5,'Trening bez pritiska','training',{},'Opcioni prostor za ispitivanje reči i sposobnosti bez sata i nagrada.',['battle','dictionary','training-results'],'Opciono');
S('training-results',5,'Rezultat treninga','training-results',{},'Lični napredak i pronađene reči. Ne pretvarati trening u obavezu za ekonomiju.',['training','home'],'Opciono');
S('codex',5,'Dnevnik sveta','codex',{},'Otkrivene oblasti i neprijatelji sa taktičkim beleškama. Bez spojlera za neotkrivene.',['enemy-detail','world'],'Opciono');
S('enemy-detail',5,'Dnevnik protivnika','enemy-detail',{},'Vidljiv obrazac, slabost i više mogućih odgovora, dostupni i van borbe.',['encounter','codex'],'Opciono');
S('challenge',5,'Izazov: duga reč','challenge',{},'Opcioni unapred pripremljen izazov radi raznovrsnosti. U ovoj verziji bez online rang-liste i dnevnog tajmera.',['battle','training'],'Opciono');
S('cosmetics',5,'Izgled svetionika','cosmetics',{},'Opcioni kreativni cilj: promena izgleda nagradama iz kampanje. Ne određuje model monetizacije.',['cosmetic-detail','home'],'Opciono');
S('cosmetic-detail',5,'Pregled izgleda','cosmetic-detail',{},'Poređenje izgleda i jasan uslov dobijanja. Čista kozmetika bez prednosti u borbi.',['home','cosmetics'],'Opciono');
S('settings',6,'Podešavanja','settings',{},'Zvuk, pristupačnost, jezik, čuvanje i pomoć. Povratak iz borbe čuva kontekst pauze.',['accessibility','language','save','help']);
S('accessibility',6,'Pristupačnost','accessibility',{},'Veći tekst, pojačan kontrast, manje kretanja i unos tapkanjem. Efekti ne smeju zaklanjati slova.',['settings','training']);
S('dictionary',6,'Rečnik i pravila','dictionary',{},'Objasniti minimum slova, ponavljanje, dijakritiku i jezičke pakete. Demo koristi malu probnu listu.',['word-report','language','help'],'Prototip');
S('word-report',6,'Prijava nedostajuće reči','word-report',{},'Prijava ne menja ishod borbe. U prvom prototipu samo lokalna beleška; slanje nikome nije povezano.',['report-saved','dictionary'],'Opciono');
S('report-saved',6,'Beleška o reči sačuvana','empty',{symbol:'✓',heading:'Hvala što primećuješ.',text:'Ovo je prikaz lokalne beleške za pregled rečnika. U mockupu podaci se ne šalju niti trajno čuvaju.',primary:['Nazad na pravila','dictionary'],secondary:['Nastavi borbu','battle']},'Razlikovati lokalno beleženje od uspešnog slanja na server.',['dictionary','battle'],'Opciono');
S('save',6,'Profil i čuvanje','save',{},'Lokalna kampanja može raditi offline. Cloud je budući predlog; ovaj ekran ne tvrdi da je nalog povezan.',['cloud-offline','save-conflict','reset-confirm'],'Opciono');
S('help',6,'Pomoć','help',{},'Kratka pravila, ponovno uputstvo i prijava problema, bez traženja spoljne podrške za osnovna pravila.',['dictionary','tutorial-word','feedback','credits']);
S('feedback',6,'Prijava problema','feedback',{},'Pripremiti objašnjenje i kontekst; ništa se ne šalje iz prototipa.',['feedback-saved','help'],'Opciono');
S('feedback-saved',6,'Pripremljena povratna informacija','empty',{symbol:'✓',heading:'Beleška je spremna.',text:'U pravoj igri ovde bi bio pregled za slanje. Ovaj mockup ne šalje prijave, poruke ni dijagnostiku.',primary:['Nazad na pomoć','help']},'Uspeh lokalne simulacije ne sme glumiti stvarnu isporuku.',['help'],'Opciono');
S('credits',6,'O igri i materijalima','credits',{},'Mesto za autore, licence rečnika, verziju i pravila privatnosti kada postoje stvarne integracije.',['help','home']);
S('reset-confirm',6,'Potvrda brisanja profila','reset',{},'Destruktivnu akciju odvojiti od običnih podešavanja. U atlasu se brisanje samo simulira.',['save','profile'],'Opciono');
S('resume',7,'Povratak u igru','modal',{base:'battle',symbol:'↻',heading:'Dobro došao nazad.',text:'Borba je zaustavljena dok si bio odsutan. Nastavi kad budeš spreman.',primary:['Nastavi borbu','battle'],secondary:['Vrati se u bazu','quit']},'Poziv, zaključavanje i promena aplikacije ne smeju doneti nevidljivu štetu.',['battle','quit'],'Prototip');
S('touch-cancel',7,'Sistem je prekinuo dodir','battle',{message:'Unos je otkazan · slova i energija su sačuvani.'},'pointercancel/OS prekid ne šalje polovičnu reč. U pravoj borbi sačuvati skup i preći na pauzu ako je aplikacija u pozadini.',['word-drag','resume'],'Prototip');
S('loading',7,'Učitavanje oblasti','loading',{},'Prikaz napretka bez tvrdnje da je zaleđeni procenat stvarno preuzimanje. Demo ima ručno Nastavi.',['encounter','download-error']);
S('download-error',7,'Jezički paket nije dostupan','empty',{symbol:'↻',heading:'Paket nije spreman.',text:'Preuzimanje nije završeno. Možeš ponovo da pokušaš ili da nastaviš sa već instaliranim srpskim paketom.',primary:['Pokušaj ponovo','loading'],secondary:['Koristi instalirani paket','home']},'Instalirani offline sadržaj ne sme biti blokiran neuspehom opcionalnog preuzimanja.',['loading','home'],'Opciono');
S('cloud-offline',7,'Offline režim','empty',{symbol:'☁',heading:'Igraj i bez signala.',text:'Kampanja i instalirani rečnik su dostupni. Povezivanje čuvanja u oblaku je buduća opcija.',primary:['Nastavi lokalno','home'],secondary:['Profil i čuvanje','save']},'Nedostatak veze nije greška osnovne offline petlje. Cloud i serveri još nisu odabrani.',['home','save'],'Opciono');
S('save-conflict',7,'Dva sačuvana napretka','save-conflict',{},'Ne prepisivati automatski. Uporediti uređaj, oblast i datum, pa potvrditi izbor.',['save-choice','save'],'Opciono');
S('save-choice',7,'Potvrda izbora napretka','modal',{base:'save',symbol:'◇',heading:'Nastaviti ovaj napredak?',text:'Izabran: ovaj uređaj, oblast 2, 18 susreta. Drugu verziju prvo sačuvati kao rezervu; detaljan sistem čuvanja nije implementiran.',primary:['Potvrdi primer izbora','save'],secondary:['Uporedi ponovo','save-conflict']},'Drugi korak pre zamene napretka. Bez brisanja bilo kojih stvarnih podataka.',['save','save-conflict'],'Opciono');
S('save-error',7,'Neuspešno lokalno čuvanje','modal',{base:'victory',symbol:'!',heading:'Nagrada čeka čuvanje.',text:'Napredak nije upisan. Oslobodi prostor i pokušaj ponovo. Ne zatvaraj igru dok se čuvanje ne završi.',primary:['Ponovi čuvanje — demo','victory'],secondary:['Prikaži pomoć','help']},'Ne prikazivati uspeh pre potvrđenog upisa. U pravoj igri potreban privremeni zapis i oporavak bez dupliranja nagrade.',['victory','help']);
S('restore-battle',7,'Oporavak nedovršene borbe','modal',{base:'home',symbol:'↺',heading:'Tvoj susret još čeka.',text:'Pronađen je sačuvan susret u Svetlucavom gaju. Nastavi ga ili bez kazne kreni iznova.',primary:['Nastavi sačuvani susret','resume'],secondary:['Pokreni ponovo','battle']},'Oporavak posle zatvaranja aplikacije ili pada; stvarni format snimka je budući tehnički zadatak.',['resume','battle']);
S('orientation',7,'Telefon u vodoravnom položaju','empty',{symbol:'▯',heading:'Uspravi svet.',text:'Za pregled borbe i slova zajedno, okreni telefon uspravno. Trenutna borba je pauzirana.',primary:['Nastavi u uspravnom prikazu','resume']},'Uspravan format je hipoteza. Okretanje ne sme izgubiti dodir, reč ili napredak.',['resume'],'Prototip');

S('upgrade-strong-confirm',3,'Potvrda jače zaštite','modal',{base:'ability',symbol:'◇',heading:'Postojana ljuska',text:'Ublažava 10 umesto 8 štete. Cena ostaje 5 energije. Izbor menja granu; poništavanje još nije dogovoreno.',primary:['Izaberi jaču zaštitu','upgrade-done'],secondary:['Uporedi ponovo','upgrade-choice']},'Potvrda mora odgovarati izabranoj grani, uz jasan prikaz posledica.',['upgrade-choice','upgrade-done']);
S('upgrade-return-done',4,'Aktivna grana povraćaja','empty',{symbol:'✧',heading:'Odbrana koja vraća glas.',text:'Povratni odjek je izabran. Pravovremen štit vraća 2 energije; ublažavanje ostaje 8. Ovo je simulacija izbora grane.',primary:['Pogledaj postavu','team'],secondary:['Nastavi ekspediciju','map']},'Posebno završno stanje za granu povraćaja energije.',['team','map']);

const FLOWS = [
  ['Prva ekspedicija','Od prvog pokretanja do razumevanja osnovne petlje.',['splash','language','profile','intro','tutorial-word','tutorial-energy','tutorial-defense','home']],
  ['Jedan dobar krug igre','Reči stvaraju resurs; igrač bira trenutak i vrstu sposobnosti.',['home','map','encounter','team','battle','word-ok','ability-cast','victory','reward','map']],
  ['Učenje iz poraza','Brz povratak uz priliku da se promeni taktika.',['enemy-warning','low-health','defeat','team','battle']],
  ['Novo otkriće','Garantovana nagrada uvodi novu taktičku odluku.',['boss-intro','boss-phase','victory','new-echo','ability','upgrade-choice','upgrade-confirm','upgrade-done','chapter-end']],
  ['Reč nije prošla','Različiti uzroci imaju različitu poruku.',['word-drag','word-invalid','word-short','word-repeat','word-report','report-saved']],
  ['Prekid bez kazne','Očuvati unos i stanje, pa nastaviti kada je igrač spreman.',['battle','touch-cancel','pause','resume','battle']],
  ['Napredak mora da preživi','Opcioni cloud tok i obavezno pošten prikaz neuspešnog čuvanja.',['victory','save-error','save','cloud-offline','save-conflict','save-choice']],
  ['Slobodno istraživanje','Kasniji sadržaji, tek posle provere osnovne borbe.',['home','quests','training','codex','collection','workshop','cosmetics']]
];
