"""Build the static support pages; no runtime or remote dependencies on the website."""
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1] / 'website' / 'wow'
pending = '<p class="notice" data-contact-pending><strong>Pre-release notice:</strong> GottaPlay is verifying its support and privacy mailboxes. The contact and data-request service is not open yet. Do not send personal information until a verified contact is published here.</p>'
pages = {
'privacy': ('Privacy policy', 'How War of Words and this website handle your information.', '''
<p class="date">Last updated: 20 September 2026 · Current development preview</p>
<p>This policy covers the War of Words Android game and its pages at gottaplay.net/wow. The publisher is <strong>GottaPlay</strong>. It does not cover other GottaPlay games or websites you reach through external links.</p>
PENDING
<h2>Information used by the game</h2>
<table><thead><tr><th>Information</th><th>Purpose and handling</th></tr></thead><tbody>
<tr><td>Local progress and preferences</td><td>Campaign progress, equipment, saved battles, scores, nickname, language and sound settings are saved on your device so you can continue playing.</td></tr>
<tr><td>Online player identity</td><td>Online features use a randomly assigned player identifier and authentication session through Supabase. No email registration is required in the current preview. Session credentials are stored on your device and used to authenticate online requests.</td></tr>
<tr><td>Daily Challenge activity</td><td>Ranked play sends the selected nickname, language, linking rule, attempt information, letter paths and move timings to the service. These are used to reconstruct and validate the result, enforce the daily attempt rules and display rankings.</td></tr>
<tr><td>Endless results</td><td>When you choose to submit an Endless run, the service receives its identifier, nickname, score, wave reached, word count, duration, language and linking rule. Unsubmitted run records remain on the device.</td></tr>
<tr><td>Connection information</td><td>Website hosting and online service providers process requests including an IP address and technical request information to deliver the service and maintain security. Log and backup retention depends on their configuration.</td></tr>
<tr><td>Messages you send us</td><td>If you contact GottaPlay, the email address, message and any attachments you provide are used to respond and handle your request. Please do not send passwords, authentication tokens or unnecessary personal information.</td></tr>
</tbody></table>
<h2>What other players can see</h2><p>Online rankings display nicknames and game results. Choose a nickname that does not reveal your real name or contact details. The leaderboard does not display your authentication credentials or internal player identifier. Reading online rankings also involves a request to the online service.</p>
<h2>Service providers and sharing</h2><p>Supabase provides authentication and database infrastructure for online play. The current project is configured in the Frankfurt region. Service operation and support may involve processing in other countries under the provider’s arrangements. See <a href="https://supabase.com/privacy">Supabase’s privacy policy</a>. Website hosting and email providers process connection data or messages as needed to operate those services. GottaPlay does not sell the game’s player data.</p>
<h2>Advertising and purchases</h2><p>The current development preview does not integrate Google AdMob or another advertising SDK and has no in-app purchases. An optional rewarded advertisement for continuing an Endless run is under consideration; it is not a feature of this version. This policy will be updated before advertising is introduced to explain the SDK, data categories, purposes, sharing and privacy choices. No advertising consent is collected by this page.</p>
<h2>This website and cookies</h2><p>The supplied War of Words pages use locally hosted images and fonts. They do not set cookies, write to browser storage, run analytics, display ads or embed social-network players. Animations respect your device’s reduced-motion setting. Opening an external link takes you to that provider’s service and privacy practices. Hosting infrastructure may keep technical access logs.</p>
<h2>Storage and deletion</h2><p>Local game data stays on the device until it is cleared or the app is removed, subject to any device backup or restore settings. Clearing local data does not delete online results and can remove the session that identifies your online profile.</p><p>The current online preview has no scheduled automatic expiry for player profiles, submitted results or daily attempt records. They remain in the service until removed by its operator. A verified deletion request should cover the profile and associated game records; limited records may need to be retained for security or legal reasons. Any applicable exception and retention period must be explained when the request is handled.</p><p class="notice">Before the public release, GottaPlay will finalize its operational retention periods, hosting and email-provider details, and the data-request contact. This pre-release policy is not a statement that those launch steps are complete.</p>
<h2>Your choices and requests</h2><p>You can play Campaign and Daily Challenge practice offline, choose a non-identifying nickname, and decide whether to submit an Endless result. For access, correction or deletion requests, see <a href="../delete-data/">Delete my data</a>. Depending on your location, you may have additional rights such as restriction, objection, portability or a complaint to your data-protection authority.</p>
<h2>Security</h2><p>Online game requests use HTTPS and authenticated service access. No service can guarantee absolute security. Do not share your saved session files or authentication tokens. Access to a device may allow access to locally stored progress and session information.</p>
<h2>Children and age suitability</h2><p>The public release’s intended age groups and store content rating have not yet been finalized. GottaPlay will align the release, online features and any advertising with that audience before launch. If you believe a child has provided personal information, contact GottaPlay through the verified privacy contact when available.</p>
<h2>Changes and contact</h2><p>Updates will be posted on this page with a revised date. Material changes to data practices will be communicated as appropriate before they take effect.</p><p>Publisher: <strong>GottaPlay</strong><br>Privacy contact: <a data-email="privacy">privacy@gottaplay.net — not yet verified</a><br>Support: <a data-email="support">hello@gottaplay.net — not yet verified</a></p>
'''),
'support': ('How can we help?', 'Support and contact information for War of Words by GottaPlay.', '''
<p>War of Words is currently in development for Android. This is the official GottaPlay support page for the game.</p>PENDING
<h2>Contact GottaPlay</h2><p>Game support: <a data-email="support">hello@gottaplay.net — not yet verified</a><br>Privacy requests: <a data-email="privacy">privacy@gottaplay.net — not yet verified</a></p>
<h2>Reporting an issue</h2><p>When the support mailbox opens, include your game version, phone model, Android version, selected language and a short description of what happened. A screenshot may help. Remove personal information from screenshots and never send passwords or session files.</p>
<h2>Progress and online results</h2><p>Saved progress is local to your device. Uninstalling the game or clearing its storage can erase progress and your online session. Cloud save and cross-device account recovery are not part of the current preview.</p><p>Ranked Daily Challenges and online leaderboards require a connection. Campaign and Daily Challenge practice can be played offline. If a submission fails, follow the game’s retry option; a local result is not a confirmed online result.</p>
<h2>Privacy or deletion</h2><p>Read the <a href="../privacy/">privacy policy</a> or visit <a href="../delete-data/">Delete my data</a> for the request procedure and the distinction between local progress and online records.</p>
<h2>Official social channels</h2><p>Our Instagram, TikTok and YouTube profiles are not live yet. Verified links will be published on the <a href="../#community">War of Words homepage</a>. No social account is required to play the current preview.</p>
'''),
'delete-data': ('Delete my data', 'Request deletion of your War of Words online profile and associated data.', '''
<p>This page explains data deletion for <strong>War of Words by GottaPlay</strong>, including the anonymous player profile used by online features.</p>PENDING
<h2>Request online-data deletion</h2><ol><li>Contact the verified privacy mailbox listed below with the subject <strong>War of Words data deletion</strong>.</li><li>Provide the nickname used, the mode, approximate date and score of a submitted result, and whether you want all associated online data deleted or only a particular result. Do not include passwords, access tokens, session files or identity documents.</li><li>GottaPlay will need to verify that the request relates to your profile. Nicknames are not unique, so a nickname alone may be insufficient. Further non-sensitive details may be requested. Keep the game installed until identity has been resolved if possible.</li></ol>
<p>Privacy contact: <a data-email="privacy">privacy@gottaplay.net — not yet verified</a></p>
<h2>What the request covers</h2><p>A full online-profile deletion request covers the anonymous authentication profile and its associated nicknames, ranked Daily Challenge attempts and move records, and submitted Endless results. Deleted results no longer appear on active leaderboards. Website access logs, provider backups and support correspondence may be handled separately under applicable retention arrangements.</p>
<h2>What remains and for how long</h2><p>The current preview does not automatically expire online game records. Any security or legal retention exception, and its duration, must be communicated when a request is processed. GottaPlay’s public-release processing times and provider backup-retention periods are still being finalized; this preview does not promise immediate automated deletion.</p>
<h2>Delete progress on your phone</h2><p>Use Android’s app storage controls to clear War of Words data, or uninstall the app. This removes local progress and preferences, subject to device backups. <strong>This does not remove online records.</strong> It can also remove the session used to identify your online profile, so request online deletion first where possible.</p>
<h2>Before the service opens</h2><p>The current app has no in-app account-deletion control, and this static page cannot delete server data itself. GottaPlay will complete and verify the contact, ownership-check and deletion process before public launch. No request is submitted simply by reading this page.</p>
<p>For more details, read the <a href="../privacy/">privacy policy</a>.</p>
'''),
'terms': ('Terms of use', 'Terms for the War of Words development preview and website.', '''
<p class="date">Last updated: 20 September 2026</p><p>These terms cover the War of Words development preview and its website, published by <strong>GottaPlay</strong>.</p>
<h2>The preview</h2><p>The game is in development. Features, balance, availability and compatibility may change. Preview progress and online records may not carry over into a future release. Keep this in mind when testing.</p>
<h2>Fair play</h2><p>Use the game lawfully. Do not attempt to compromise its services, impersonate others, submit manipulated results or use offensive or identifying nicknames. Online rankings are provided for entertainment; they are not prize competitions.</p>
<h2>Game materials</h2><p>Game artwork, branding and code are provided for use with the game and this site. Third-party components retain their own licenses; the game includes its credits and license notices. This website’s local fonts are distributed under the SIL Open Font License.</p>
<h2>Availability and purchases</h2><p>The current preview has no in-app purchases or advertising SDK. Any future commercial features will be explained before they become available. GottaPlay does not promise uninterrupted online access or permanent storage of preview progress.</p>
<h2>Privacy and contact</h2><p>The <a href="../privacy/">privacy policy</a> explains data handling. Contact details and reporting instructions are on the <a href="../support/">support page</a>.</p>
<h2>Your rights</h2><p>Nothing in these terms excludes rights or protections that cannot be excluded under applicable law. Material changes will be published here with an updated date.</p>
''')}

for slug, (title, description, body) in pages.items():
    body = body.replace('PENDING', pending)
    html = f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{title} — War of Words | GottaPlay</title><meta name="description" content="{description}"><meta name="theme-color" content="#07171f"><link rel="canonical" href="https://gottaplay.net/wow/{slug}/"><link rel="icon" href="../assets/icon.webp"><link rel="stylesheet" href="../styles.css"><script src="../site-config.js" defer></script><script src="../site.js" defer></script></head>
<body><a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="../"><img src="../assets/icon.webp" width="42" height="42" alt=""><span>WAR <small>OF</small> WORDS</span></a><nav aria-label="Main navigation"><a class="nav-cta" href="../">Back to the game ↗</a></nav></header>
<main id="main" class="legal section"><p class="eyebrow">GottaPlay / War of Words</p><h1>{title}</h1>{body}</main>
<footer class="site-footer"><div class="footer-bottom"><a class="publisher-credit" href="https://gottaplay.net/"><img class="gottaplay-mark" src="../assets/gottaplay-logo.png" width="30" height="30" alt=""><span>© 2026 GottaPlay · War of Words</span></a><nav aria-label="Legal and support"><a href="../">The game</a><a href="../privacy/">Privacy</a><a href="../support/">Support</a><a href="../delete-data/">Delete my data</a><a href="../terms/">Terms</a></nav></div></footer></body></html>'''
    dest = ROOT / slug / 'index.html'
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(html, encoding='utf-8')
print('Built four static support and policy pages.')
