"""Compile reviewed language patterns into exact dictionary exclusions, without modifying source dictionaries."""
from pathlib import Path
import gzip
import json
import re

ROOT = Path(__file__).resolve().parent.parent
rules = json.loads((ROOT / 'tools/content-filter-rules.json').read_text(encoding='utf-8'))
blocked = {}
for code, rule in rules.items():
    name = 'english.txt' if code == 'en' else ('serbian.txt.gz' if code == 'sr' else f'{code}.txt.gz')
    raw = (ROOT / 'game/data' / name).read_bytes()
    text = (gzip.decompress(raw) if name.endswith('.gz') else raw).decode('utf-8')
    pattern = re.compile('|'.join(rule['patterns']), re.IGNORECASE)
    blocked[code] = sorted({word.upper() for word in text.splitlines() if pattern.search(word.upper())})
    print(f'{code}: {len(blocked[code])} blocked dictionary entries')
payload = json.dumps(blocked, ensure_ascii=False, indent=2) + '\n'
(ROOT / 'game/data/blocked-words.json').write_text(payload, encoding='utf-8')
(ROOT / 'supabase/functions/daily/content-filter.mjs').write_text(
    '// Generated by tools/build-content-filter.py; do not edit.\n'
    + 'const BLOCKED_WORDS = ' + payload.rstrip() + ';\n'
    + 'const BLOCKED = Object.fromEntries(Object.entries(BLOCKED_WORDS).map(([code, words]) => [code, new Set(words)]));\n'
    + 'export function contentAllowed(word, language) { return !!BLOCKED[language] && !BLOCKED[language].has(word.toUpperCase()); }\n', encoding='utf-8')
